name: CI

on: [push, repository_dispatch]

jobs:
  test:
    name: Build and run tests
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout testbed
        uses: actions/checkout@v3
        with:
          path: live_state_testbed
      - name: Checkout live_state
        uses: actions/checkout@v3
        with:
          repository: launchscout/live_state
          path: live_state
      - name: Checkout phx-live-state
        uses: actions/checkout@v3
        with:
          repository: launchscout/phx-live-state
          path: phx-live-state
      - name: Set up Elixir
        uses: erlef/setup-beam@v1
        with:
          otp-version: '25.1' # Define the OTP version [required]
          elixir-version: '1.14.0' # Define the elixir version [required]
      - name: install phx-live-state assets
        run: npm install
        working-directory: phx-live-state
      - name: build phx-live-state
        run: npm run build
        working-directory: phx-live-state
      - name: Install testbed dependencies
        run: mix deps.get
        working-directory: live_state_testbed
      - name: install testbed assets
        run: npm install
        working-directory: live_state_testbed/assets
      - name: build testbed javascript
        run: mix esbuild default
        working-directory: live_state_testbed
      - name: Run testbed integration tests
        run: mix test
        working-directory: live_state_testbed

