name: CI

on: push

jobs:
  test:
    name: Build and run tests
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout project
        uses: actions/checkout@v3
      - name: Set up Elixir
        uses: erlef/setup-beam@v1
        with:
          otp-version: '25.1' # Define the OTP version [required]
          elixir-version: '1.14.0' # Define the elixir version [required]
      - name: Restore dependencies cache
        uses: actions/cache@v2
        with:
          path: live_state/deps
          key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
          restore-keys: ${{ runner.os }}-mix-
      - uses: actions/cache@v1
        name: Cache build
        with:
          path: live_state/_build
          key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
      - name: Install dependencies
        run: mix deps.get
        working-directory: live_state
      - name: Run live_state elixir tests
        run: mix test
        working-directory: live_state
      - name: npm install phx-live-state
        run: npm install
        working-directory: phx-live-state
      - name: Run phx-live-state tests
        run: npm test
        working-directory: phx-live-state
      - name: build phx-live-state
        run: npm run build
        working-directory: phx-live-state
      - name: Install testbed dependencies
        run: mix deps.get
        working-directory: testbed
      - name: npm install testbed assets
        run: npm install
        working-directory: testbed/assets
      - name: build testbed javascript
        run: mix esbuild default
        working-directory: testbed/assets
      - name: Run testbed integration tests
        run: mix test
        working-directory: testbed
